"""Person table with constraints table

Revision ID: 5807795eced3
Revises: 
Create Date: 2025-03-25 21:12:11.792144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5807795eced3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('profession', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_id'), 'persons', ['id'], unique=False)
    op.create_table('constraints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('day', sa.Enum('Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche', name='dayenum'), nullable=True),
    sa.Column('slot', sa.Enum('Jour', 'Matin', 'Après_midi', 'Nuit', name='slotenum'), nullable=True),
    sa.Column('constraint_type', sa.Enum('CP', 'RTT', 'Formation', 'Reunion', 'GroupeDeTravail', 'Present', name='constrainttypeenum'), nullable=True),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('constraints')
    op.drop_index(op.f('ix_persons_id'), table_name='persons')
    op.drop_table('persons')
    # ### end Alembic commands ###
